hostname: "http://yourdomain.com"
basepath: ""

title: Finding The Way Home
description: >
  A beautiful narrative written with the world's most elegant
  publishing platform. The story begins here.
cover: "/assets/images/home1.jpg"
logo: "/assets/images/ghost.png"

navigation:
  Home: "/"
  About: "/about/"
  Fables: "/tag/fables/"
  Speeches: "/tag/speeches/"

authors:

  "Abraham Lincoln":
    bio: >
      I was the 16th president of the USA until I was assassinated in
      April of 1963. I led the US through its Civil War - its
      bloodiest and greatest moral, constitutional and political
      crisis.
    image: "/assets/images/abe.jpg"
    location: "Kentucky, USA"

  "Edgar Rice Burroughs":
    bio: >
      I'm an American novelist, best known for my work writing about a
      brave jungle hero called Tarzan and his muse, Jane.
    image: "/assets/images/edgar.gif"
    location: "Chicago, Illinois"

  "Lewis Carroll":
    bio: >
      My real name is Charles Lutwidge Dodgson, but people call me
      Lewis. I'm an English writer, mathematician, logician, Anglican
      deacon and photographer. People know me best for writing about
      Alice.
    image: "/assets/images/lewis.jpeg"
    location: "Cheshire, England"

  "Martin Luther King":
    bio: >
      An American pastor, activist, humanitarian. People know me for
      leading the African-American Civil Rights movement using
      nonviolent civil disobedience.
    image: "/assets/images/mlk.jpg"
    location: "Memphis, Tennessee"

  "Nikolai Frits":
    bio: "I share links on writing, publishing & new media."
    cover: "/assets/images/cover4.jpg"
    image: "/assets/images/avatar2.jpg"
    location: "London, UK"
    website: "http://bit.ly/1nP8GsR"

  "Otho Korbin":
    bio: "I am taking full advantage of long summer days and warm weather."
    cover: "/assets/images/cover3.jpg"
    image: "/assets/images/avatar1.jpg"
    location: "On a plane"
    website: "http://bit.ly/1TKGbcn"

tags:
  Fables:
    description: A series of short stories that make you think.
    image: "/assets/images/cover2.jpg"
  Speeches:
    description: Some of the greatest words ever spoken.
    image: "/assets/images/cover1.jpg"
